version: '2'

networks:
  internal:
    driver: bridge

services:

  redis:
    image: redis
    networks:
     internal:
       aliases:
        - redis-alias

  cassandra:
    image: chadmoon/cassandra-spinnaker
    networks:
     internal:
       aliases:
        - cassandra-alias
    environment:
      CASSANDRA_START_RPC: "true"

  front50:
    image: java:8
    networks:
     internal:
       aliases:
        - front50-alias
    volumes:
     - ./services/front50:/app
    entrypoint: /bin/bash
    command: ['-c', 'cd /app; GRADLE_USER_HOME=cache ./gradlew bootRun']

  clouddriver:
    image: java:8
    networks:
     internal:
       aliases:
        - clouddriver-alias
    volumes:
     - ./services/clouddriver:/app
    entrypoint: /bin/bash
    command: ['-c', 'cd /app; GRADLE_USER_HOME=cache ./gradlew bootRun']

  orca:
    image: java:8
    networks:
     internal:
       aliases:
        - orca-alias
    volumes:
     - ./services/orca:/app
    entrypoint: /bin/bash
    command: ['-c', 'cd /app; GRADLE_USER_HOME=cache ./gradlew bootRun']

  gate:
    image: java:8
    networks:
     internal:
       aliases:
        - gate-alias
    volumes:
     - ./services/gate:/app
    entrypoint: /bin/bash
    command: ['-c', 'cd /app; GRADLE_USER_HOME=cache ./gradlew bootRun']

#   clouddriver:
#     image: quay.io/spinnaker/clouddriver
#     networks:
#      internal:
#        aliases:
#         - clouddriver-alias
#     volumes_from:
#      - configdata
#     volumes:
#      - ./minikube.config:/root/.kube/config
#      - ~/.minikube/apiserver.crt:/root/.kube/apiserver.crt
#      - ~/.minikube/apiserver.key:/root/.kube/apiserver.key
#     depends_on:
#      - front50
#      - redis

#   rosco:
#     image: quay.io/spinnaker/rosco
#     networks:
#      internal:
#        aliases:
#         - rosco-alias
#     depends_on:
#      - clouddriver
#     volumes_from:
#      - configdata

#   orca:
#     image: quay.io/spinnaker/orca
#     networks:
#      internal:
#        aliases:
#         - orca-alias
#     depends_on:
#      - rosco
#     volumes_from:
#      - configdata

#   echo:
#     image: quay.io/spinnaker/echo
#     networks:
#      internal:
#        aliases:
#         - echo-alias
#     depends_on:
#      - orca
#     volumes_from:
#      - configdata

#   gate:
#     image: quay.io/spinnaker/gate
#     networks:
#      internal:
#        aliases:
#         - gate-alias
#     depends_on:
#      - echo
#     volumes_from:
#      - configdata

#   deck:
#     image: nginx
#     networks:
#       - internal
#       - default
#     depends_on:
#      - gate
#     volumes:
#      - ./deck:/opt/deck
#      - ./nginx.conf:/etc/nginx/nginx.conf
#     ports:
#      - "9000:80"