version: '2'

networks:
  internal:
    driver: bridge

services:

  pingbox:
    image: chadmoon/nmap
    networks:
      internal:
        aliases:
        - nmap-alias

  redis:
    image: redis
    networks:
     internal:
       aliases:
        - redis-alias

  cassandra:
    image: chadmoon/cassandra-spinnaker
    networks:
     internal:
       aliases:
        - cassandra-alias
    environment:
      CASSANDRA_START_RPC: "true"

  front50:
    image: java:8
    networks:
     internal:
       aliases:
        - front50-alias
    volumes:
     - ./services/front50:/app
    entrypoint: /bin/bash
    command: ['-c', 'cd /app; GRADLE_USER_HOME=cache ./gradlew bootRun']

  clouddriver:
    image: java:8
    env_file: .env
    networks:
     internal:
       aliases:
        - clouddriver-alias
    volumes:
     - ./services/clouddriver:/app
    entrypoint: /bin/bash
    command: ['-c', 'cd /app; GRADLE_USER_HOME=cache ./gradlew bootRun']

  orca:
    image: java:8
    networks:
     internal:
       aliases:
        - orca-alias
    volumes:
     - ./services/orca:/app
    entrypoint: /bin/bash
    command: ['-c', 'cd /app; GRADLE_USER_HOME=cache ./gradlew bootRun']

  gate:
    image: java:8
    networks:
      internal:
        aliases:
         - gate-alias
      default:
        aliases:
         - gate-external
    ports:
     - "8084:8084"
    volumes:
     - ./services/gate:/app
    entrypoint: /bin/bash
    command: ['-c', 'cd /app; GRADLE_USER_HOME=cache ./gradlew bootRun']

  rosco:
    image: java:8
    networks:
      internal:
        aliases:
         - rosco-alias
    ports:
     - "8087:8087"
    volumes:
     - ./services/rosco:/app
    entrypoint: /bin/bash
    command: ['-c', 'cd /app; GRADLE_USER_HOME=cache ./gradlew bootRun']

  deck:
    image: nginx
    networks:
      internal:
        aliases:
         - deck-alias
      default:
        aliases:
         - deck-external
    ports:
     - "9000:80"
    volumes:
     - ./services/deck/build/webpack:/opt/deck
     - ./config/nginx.conf:/etc/nginx/nginx.conf