version: '2'

networks:
  internal:
    driver: bridge

services:

  pingbox:
    image: chadmoon/nmap
    networks:
      internal:
        aliases:
        - nmap-alias

  redis:
    image: redis
    networks:
     internal:
       aliases:
        - redis-alias

  cassandra:
    image: chadmoon/cassandra-spinnaker
    networks:
     internal:
       aliases:
        - cassandra-alias
    environment:
      CASSANDRA_START_RPC: "true"

  front50:
    image: java:8
    networks:
     internal:
       aliases:
        - front50-alias
    volumes:
     - ./services/front50:/app
    entrypoint: /bin/bash
    command: ['-c', 'cd /app; GRADLE_USER_HOME=cache ./gradlew bootRun']

  clouddriver:
    image: java:8
    env_file: .env
    networks:
     internal:
       aliases:
        - clouddriver-alias
    volumes:
     - ./services/clouddriver:/app
    entrypoint: /bin/bash
    command: ['-c', 'cd /app; GRADLE_USER_HOME=cache ./gradlew bootRun']

  orca:
    image: java:8
    networks:
     internal:
       aliases:
        - orca-alias
    volumes:
     - ./services/orca:/app
    entrypoint: /bin/bash
    command: ['-c', 'cd /app; GRADLE_USER_HOME=cache ./gradlew bootRun']

  gate:
    image: java:8
    networks:
      internal:
        aliases:
         - gate-alias
      default:
        aliases:
         - deck-external
    ports:
     - "8084:8084"
    volumes:
     - ./services/gate:/app
    entrypoint: /bin/bash
    command: ['-c', 'cd /app; GRADLE_USER_HOME=cache ./gradlew bootRun']

  deck:
    image: chadmoon/dockernginx
    networks:
      - internal
    entrypoint: /bin/bash
    command: ['-c', 'cd /app; npm install; npm run build; mv /app/build/webpack /opt/deck; nginx -g "daemon off;"']
    volumes:
     - ./services/deck:/app
    ports:
     - "9000:80"
    environment: ['CI=true','AUTH_ENABLED=true', 'API_HOST=http://localhost:8084/', 'BAKERY_DETAIL_URL=http://localhost:8087/']