aws:
  enabled: true
  defaults:
    iamRole: BaseIAMRole
  defaultRegions:
    - name: us-east-1
  defaultFront50Template: http://front50-alias:8080
  defaultKeyPairTemplate: keypair
  migration:
    infrastructureApplications: null
  # an empty list means we are directly managing the AWS account we have credentials for (named default.account.env)
  # see prod profile section below for an example configuration to manage other accounts via STS assume role
  accounts: []


azure:
  enabled: false
cf:
  accounts:
  enabled: false
credentials:
  challengeDestructiveActionsEnvironments: default
  primaryAccountTypes: default
default:
  account:
    env: default



google:
  enabled: false
kubernetes:
  enabled: false

dockerRegistry:
  enabled: false

redis:
  connection: redis://redis-alias:6379
  scheduler: default
  parallelism: -1
server:
  port: 7002
services:
  front50:
    baseUrl: http://front50-alias:8080
udf:
  enabled: false
