redis:
  connection: redis://redis-alias:6379
server:
  port: 8084
services:
  clouddriver:
    baseUrl: http://clouddriver-alias:7002
  deck:
    baseUrl: http://localhost:9000
  front50:
    baseUrl: http://front50-alias:8080
  orca:
    baseUrl: http://orca-alias:8083
  igor:
    enabled: true
    baseUrl: http://igor-alias:8088
  rosco:
    enabled: false
    baseUrl: http://rosco-alias:8087
