server:
  port: 8088

jenkins:
  enabled: true
  masters:
    - name: jenkins
      address: http://jenkins-aliass:8080/
      username: jenkins
      password: jenkins

travis:
  enabled: false

dockerRegistry:
  enabled: true

redis:
  connection: redis://redis-alias:6379

services:
  clouddriver:
    baseUrl: http://clouddriver-alias:7002
  echo:
    baseUrl: http://echo-alias:8089